[package]
name = "hc_zome_file_storage_gateway_integrity"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_zome_file_storage_gateway_integrity"

[dependencies]
hdi = { workspace = true }

serde = { workspace = true }
