name: "test"
on:
  push:
    branches: [ main, main-0.6, main-0.7 ]
  pull_request:
    branches: [ main, main-0.6, main-0.7 ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install nix
        uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v17
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v17
        with:
          name: holochain-open-dev

      - uses: cachix/cachix-action@v17
        with:
          name: darksoil-studio

      - name: Install and test
        run: |
          nix develop --command bash -c "npm i && npm t && npm run -w @holochain-open-dev/file-storage build"
